#+title: Bosque Argenteo

* Personaje
Soy Zobark, un semi orco quien se crió en un campamento en la montaña, mi pequeño pueblo adora la naturaleza y prefiere vivir en comumnión con los animales.
    Respetamos la vida y honramos la muerte, llevamos la piel de nuestras presas para simbolizar el respeto a ellas, al criarme en las montañas aprendí
    de los animales mis estilos de lucha, mis padres me enseñaron la meditación desde joven lo cual me llevó a un camino de serenidad y templanza.
    Prefiero utilizar mis puños para luchar y mi cuerpo para defenderme, aprendiendo de los animales de mi entorno los estilos de lucha que me ayuden
    a sobrevivir ante cualquier situación.

    Hace unas semanas cumplí mis 20 años y mis padres me recomendaron comenzar a conocer el resto del mundo, por lo cual salí en busca de aventuras
    donde conocí a un grupo de aventureros quienes parecían necesitar ayuda en su búsqueda, donde ví una oportunidad de ofrecer mi ayuda

    Karla - Riniya
    Ale - Jane
    Mel - Lini
    Jose - Jorgen
    Karoll - Gytha

    Buscamos el Orbe Estrellado
    Ofrecen diner
    Nos despiertan en la taberna para comer sopa de arroz con huevo flotando y vino diluido
    rojito se arranca, lo rastreo y ya se comio toda la comida

    2 espada cortas - a Lini
    7 frascos de vidrio con liquido sin identificar - me quedan 6 lance uno para ver si explota
    Armadura cuero re lindi - a Lini
    3 raciones viaje - pa Zobark
    1 botella liquido espeso color morado -  Veneno - a Gytha
    2 botellas liquido menos denso color rojo - Poción curar heridas ligeras - una a Jorgen, una a riniya, se curó.
    13 monedas oro
    7 oro 4 cobre

    nos pusieron una trampa, ghoul reanimado, no muerto.


    se ve estructura a la derecha, gytha identifica templo hundido, se ve techo

    Al bajar me caigo mal, casi muerto, manos me atrapan y me libero, sobrevivo pelea, jorgen me trae pocion de cura y me siento mejor
    jorgen esta mirando nueva habitación, llama a Jane para identificar lenguaje



    Encontramos una puerta, gytha detecta mecanismos y encuentra marcas de manos, las mete y se las atravieza, la puerta se abre
    Nos encontramos con Egol archidruida del bosque, atrapado con raices

    Estamos en el bosque de Denot

    intento golpear el cuchico de caza para golpear la raiz y se rompe, la raiz no se inmuta.

    comienza jefe final despues de jorgen matar al viejo
    9 hp inicial
    -3 dmg
    -4 dmg
    2 hp restante
    -5 a piso

    antes de morir hasta 14
    - 3
    - 1
    - 1
    - 3
      Riniya mata a Egol y salva la partida
      + 600 G
